name: frontend-feature
description: Full frontend feature development workflow with preview

inputs:
  port:
    type: string
    description: Port to run the dev server on
    default: "3000"

env:
  NODE_ENV: development

stages:
  - name: setup
    description: Initialize workspace and install dependencies
    steps:
      - name: Create git worktree
        action: git/worktree
        with:
          base_branch: ${{ git.base_branch }}
          branch_prefix: feat/
          
  - name: implement
    description: Execute main agent work
    timeout: 30m
    steps:
      - name: Run agent implementation
        action: cursor/agent
        with:
          model: sonnet-4.5-thinking
        handlers:
          on_approve:
            - name: Commit changes
              action: git/commit
              with:
                message: "feat: ${{ workflow.task }}"
            - name: Merge worktree
              action: git/merge
            - name: Delete worktree
              action: git/worktree
              with:
                action: remove
          on_reject:
            - name: Delete worktree
              action: git/worktree
              with:
                action: remove
