name: frontend-feature
description: Full frontend feature development workflow with preview

inputs:
  port:
    type: string
    description: Port to run the dev server on
    default: "3000"

stages:
  - name: setup
    description: Initialize workspace and install dependencies
    steps:
      - name: Create git worktree
        action: git/worktree
        with:
          base_branch: ${{ git.base_branch }}
          branch_prefix: feat/
      - name: Run agent implementation
        action: cursor/agent
        with:
          model: sonnet-4.5-thinking
        handlers:
          on_approve:
            - name: Commit changes
              action: git/commit
              with:
                message: "feat: ${{ workflow.task }}"
            - name: Merge worktree
              action: git/merge
              with:
                base_branch: ${{ git.current_branch }}
                message: "Merge ${{ git.branch }} into ${{ git.current_branch }}"
            - name: Delete worktree
              action: git/worktree
              with:
                action: remove
