# fleet CLI completions (auto-generated by fleet install)
function __fleet_features
    set -l reg "$HOME/.claude/fleet/registry.json"
    test -f "$reg" && jq -r '.features | keys[]' "$reg" 2>/dev/null
end

complete -c fleet -f
complete -c fleet -n '__fish_use_subcommand' -a 'spawn' -d 'Create a new feature session'
complete -c fleet -n '__fish_use_subcommand' -a 'status' -d 'Snapshot of all active features'
complete -c fleet -n '__fish_use_subcommand' -a 'check' -d 'Detailed state of one feature'
complete -c fleet -n '__fish_use_subcommand' -a 'check-active' -d 'State of working/picker/blocked sessions'
complete -c fleet -n '__fish_use_subcommand' -a 'pr' -d 'Monitor PR: CI, reviews, comments, merge state'
complete -c fleet -n '__fish_use_subcommand' -a 'poll' -d 'Non-blocking event + state check (used by hooks)'
complete -c fleet -n '__fish_use_subcommand' -a 'send' -d 'Send text to a session'
complete -c fleet -n '__fish_use_subcommand' -a 'send-multi' -d 'Send message to multiple sessions'
complete -c fleet -n '__fish_use_subcommand' -a 'watch' -d 'Block until fleet events occur'
complete -c fleet -n '__fish_use_subcommand' -a 'kill' -d 'Kill feature sessions'
complete -c fleet -n '__fish_use_subcommand' -a 'list' -d 'List fleet-managed tmux sessions'
complete -c fleet -n '__fish_use_subcommand' -a 'pick' -d 'Select option in a picker'
complete -c fleet -n '__fish_use_subcommand' -a 'keys' -d 'Send raw tmux keys'
complete -c fleet -n '__fish_use_subcommand' -a 'recover' -d 'Reconcile registry after restart'
complete -c fleet -n '__fish_use_subcommand' -a 'prune' -d 'Trim events.jsonl'
complete -c fleet -n '__fish_use_subcommand' -a 'desc' -d 'Update feature description'
complete -c fleet -n '__fish_use_subcommand' -a 'repos' -d 'Manage repo shortname index'
complete -c fleet -n '__fish_use_subcommand' -a 'relay' -d 'Relay output from one session to another'
complete -c fleet -n '__fish_use_subcommand' -a 'share' -d 'Share a file with multiple sessions'
complete -c fleet -n '__fish_use_subcommand' -a 'install' -d 'Install fleet to ~/.local/bin'
complete -c fleet -n '__fish_use_subcommand' -a 'uninstall' -d 'Remove fleet from ~/.local/bin'

# Status flags
complete -c fleet -n '__fish_seen_subcommand_from status' -l dump -d 'Include full pane output for every session'
complete -c fleet -n '__fish_seen_subcommand_from status' -l lines -d 'Lines of scrollback with --dump' -r

# Feature name completions for commands that take a feature argument
complete -c fleet -n '__fish_seen_subcommand_from check' -a '(__fleet_features)'
complete -c fleet -n '__fish_seen_subcommand_from pr' -a '(__fleet_features)'
complete -c fleet -n '__fish_seen_subcommand_from send' -a '(__fleet_features)'
complete -c fleet -n '__fish_seen_subcommand_from kill' -a '(__fleet_features)'
complete -c fleet -n '__fish_seen_subcommand_from pick' -a '(__fleet_features)'
complete -c fleet -n '__fish_seen_subcommand_from keys' -a '(__fleet_features)'
complete -c fleet -n '__fish_seen_subcommand_from desc' -a '(__fleet_features)'
complete -c fleet -n '__fish_seen_subcommand_from relay' -a '(__fleet_features)'
